### ISSUE TITLE
Expected Maven project with dependencies

### ISSUE THREAD

**Issue by averikitsch** [googleapis/google-cloudevents-java#2]
## Actual Behavior

* Not maven project format (needed to publish to maven central) I would expect this to be in the form of a [Maven project](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html) with a pom.xml ([example](https://github.com/googleapis/java-pubsub/blob/master/pom.xml)). Jeff Ching would know more about the Yoshi Java generation process. 
* Improper file linting (spacing)
* Parent class Data has no functionality? Instead the child class of `MessagePublishedData` has the getter/setters I would expect to get the `PubsubMessage`.  Without the pom.xml with dependencies it's hard to know if this library would work as expected substitute for the POJOs in the current samples.

**Comment by grant** [comment]
```
mvn -B archetype:generate \
-DgroupId=com.google.events \
-DartifactId=google-cloudevent-types \
-DarchetypeArtifactId=maven-archetype-quickstart \
-DarchetypeVersion=1.4
```

This setup should scaffold a project.

**Comment by grant** [comment]
#8 will fix this.
