### ISSUE TITLE
Setup Release Tooling

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-java#3]
This issue tracks the release tooling for this repo.

Possibly setup Release Please:
https://github.com/googleapis/release-please/

**Comment by grant** [comment]
Maybe we can use GitHub packages?

```
mvn deploy -Dregistry=https://maven.pkg.github.com/googleapis -Dtoken=GH_TOKEN
```

**Comment by grant** [comment]
Will talk to @chingor13 about this soon – in design doc stage.

**Comment by grant** [comment]
There's a plug-in we should add to make `mvn deploy` work:

https://github.com/googleapis/java-shared-config/blob/a0120d20589240e095499598ad277b2683f86ba9/pom.xml#L70-L81

Looks fairly simple.

**Comment by chingor13** [comment]
0.1.0 release went out today!
