### ISSUE TITLE
Firestore event json to DocumentEventData parse error

### ISSUE THREAD

**Issue by czarekstasiakk** [googleapis/google-cloudevents-java#65]
## Expected Behavior
Firestore event json is proplerly parsed  by cloud function

## Actual Behavior
Cloud function exception on value.createTime field
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line x column y path $.value.createTime

## Steps to Reproduce the Problem
test:
```java
    @Test
    void should_parse_sample_event() {
        String sampleEventJson = "{\"oldValue\":{},\n" +
                "\"updateMask\":{},\n" +
                "\"value\":{\"createTime\":\"2021-02-17T13:44:56.719439Z\",\"fields\":{\"test\":{\"stringValue\":\"123\"}},\n" +
                "\"name\":\"projects/test/databases/(default)/documents/test/cY766uyH9DlcM5dzTGJ7\",\"updateTime\":\"2021-02-17T13:44:56.719439Z\"}}";
        Gson gson = new Gson();
        assertThrows(JsonSyntaxException.class, () -> gson.fromJson(sampleEventJson, DocumentEventData.class));
    }
```
or

create cloud function that is triggered by document.create on Firestore collection.
sample code:
```java
public class SampleClass implements BackgroundFunction<DocumentEventData> {

    public SampleClass() {
        ...
    }

    @Override
    public void accept(DocumentEventData payload, Context context) throws Exception {
        ...
   }
```
then trigger it by adding document to given collection
## Conclusions:
createTime and updateTime is not parsed to OffsetDateTime.

**Comment by grant** [comment]
Hi there,
Thanks for the issue and thanks for finding this library.

While Google Cloud Functions does support Firestore events, it doesn't support CloudEvents yet (only .NET, Ruby, PHP). That said, I believe the JSON payload is the same for both types.

Here's our official sample for Java:

https://cloud.google.com/functions/docs/calling/cloud-firestore#functions_firebase_firestore-java

---

For parsing the `string` to `java.time.OffsetDateTime` with `gson`, you might be able to `registerTypeAdapter` for this type conversion.

https://stackoverflow.com/a/60724813

I'll keep this issue open in case there are comments.

**Comment by grant** [comment]
This parsing type would also be needed for Pub/Sub where it uses `OffsetDateTime`.
